# Generated by cucumber-sinatra. (2014-09-11 18:53:55 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app', 'server.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'haml'
require 'sinatra/flash'

Capybara.app = Chitr

class ChitrWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ChitrWorld.new
end
